#!/bin/bash

# Install/submodule add -f Oh My Zsh by Robby Russel
wget --no-check-certificate http://install.ohmyz.sh -O - | sh

# Install Vundle https://github.com/gmarik/Vundle.vim
git clone git://github.com/gmarik/vundle.git $target/.vim/bundle/vundle

vim +BundleInstall! +qall #2&> /dev/null


bash $target/.vim/bundle/YouCompleteMe/install.sh


